### ISSUE TITLE
Compliments

### ISSUE THREAD

**Issue by Chloeh24** [fac19/week10-metalHeads#39]
Great idea! Really fun game to test my GoT knowledge :100: 

Awesome styling, I love the end game pictures depending on your score! 
Great touch adding an easy and hard mode too

Super readable code and intuitive naming conventions (especially decodeJSONOrDie :laughing: )

**Comment by Alexreid95** [comment]
-Love the game guys!!
- Like how you structured the files, very organised, with separate style sheets too!  
-Nice clear logic, very readable code!
