### ISSUE TITLE
Github Username

### ISSUE THREAD

**Issue by Chloeh24** [fac19/week10-metalHeads#43]
- If you don't type in a name, the game starts anyway with no name. Adding a default name like 'guest' might be better.

- game remembers last user after you press 'New Game'. You could either reset githubName state when the button is clicked, or have the last username show as a placeholder

- Adding an incorrect github name throws an error in the console but doesn't affect the game. Could check if username is valid before allowing gameplay

**Comment by tacotoemeck** [comment]
Great, all fixed now :D
