### ISSUE TITLE
Project organisation

### ISSUE THREAD

**Issue by oliverjam** [fac19/week10-metalHeads#46]
There are quite a lot of components + styles files in a single folder. It can be a little hard to scan, since most components have an associated CSS file with the same name. A common React pattern is to use a subdirectory for each component, containing the JS, CSS and test file for each.

E.g.
```
StartPageForm/
 | StartPageForm.js
 | StartPageForm.css
 | StartPageForm.test.js
```
etc

**Comment by Roger-Heathcote** [comment]
Done. Thanks for the tip.
